/***
**** THIS IS A TEMPLATE FILE TO HELP YOU CREATE YOUR O/S SPECIFIC PORTION.
**** DO NOT EDIT THIS FILE. COPY IT AND THEN MAKE CHANGES.
****
**** Directions are contained throughout this file in comments
**** much like this one. Feel free to delete the directions
**** when you are done.
****
**** Change all the _XXX's to reflect your NDMOS_IDENT()
***/

/***
**** Insert your Copyright notice and disclaimers
***/
/*
 * Copyright ...
 */
/*
 * Copyright (c) 1998,1999,2000
 *	Traakan, Inc., Los Altos, CA
 *	All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 * 1. Redistributions of source code must retain the above copyright
 *    notice unmodified, this list of conditions, and the following
 *    disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the
 *    documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
 * OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
 * OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*
 * Project:  NDMJOB
 * Ident:    $Id: ndmos_xxx.h,v 1.1.1.1 2003/10/14 19:18:16 ern Exp $
 *
 * Description:
 *	This establishes the environment and options
 *	for the XXX platform. This, combined with
 *	the O/S generic ndmos.h, are the foundation
 *	for NDMJOBLIB.
 *
 *	This file is #include'd by ndmos.h when
 *	selected by #ifdef's of NDMOS_ID.
 *
 *	Refer to ndmos.h for explanations of the
 *	macros thar are or can be #define'd here.
 */

/***
**** Establish your NDMOS_IDENT() and your auto-recognizer.
**** This is redundant in this file as NDMOS_ID will always
**** be defined by the time we get here. The reason to put
**** this here is the keeper of the NDMJOB sources will integrate
**** your NDMOS_IDENT() and auto-recognizer into ndmos.h Don't
**** send changes to ndmos.h for this purpose. Only send changes
**** to ndmos.h if there is some kind of problem.
***/
#define NDMOS_ID_XXX	NDMOS_IDENT('X','X','X',0)

#ifndef NDMOS_ID
#ifdef __my_cpp_cookie__
#define NDMOS_ID	NDMOS_ID_XXX
#endif /* __my_cpp_cookie__ */
#endif /* !NDMOS_ID */




#if NDMOS_ID == NDMOS_ID_XXX		/* probably redundant */

/***
**** Put #include's for your system header files here.
**** Nothing in the NDMJOB sources #include's anything
**** from "standard" places. This example here might
**** be close. This is pretty much a process of
**** trial and error.
***/
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <sys/fcntl.h>
#include <signal.h>
#include <netinet/in.h>
#include <rpc/rpc.h>
#include <assert.h>
#include <errno.h>
#include <string.h>
#include <netdb.h>
#include <ctype.h>

/***
**** You almost always have to add some extern declarations
**** for interfaces not covered by your #include files.
***/
extern long inet_addr();
extern char *inet_ntoa();

/***
**** #define NDMOS_OPTIONS_'s. See ndmos.h for a current list
**** and explanation.
***/
#define NDMOS_OPTION_HAVE_SIN_LEN
#define NDMOS_OPTION_TAPE_SIMULATOR
#define NDMOS_OPTION_USE_SELECT_FOR_CHAN_POLL

/***
**** #define NDMOS_API_'s that vary from those #define'd in ndmos.h.
***/
#define NDMOS_API_STRTOLL(P,PP,BASE) strtoq(P,PP,BASE)


/***
**** Define these macros to appropriate values.
**** Be sure to check ndmos.h for any conventions
**** on their value.
***/
/*
 * #ifndef'ed so they can be set from the Makefile command line
 */
#ifndef NDMOS_CONST_NDMJOBLIB_REVISION
#define NDMOS_CONST_NDMJOBLIB_REVISION "0"
#endif /* !NDMOS_CONST_NDMJOBLIB_REVISION */

#ifndef NDMOS_CONST_VENDOR_NAME
#define NDMOS_CONST_VENDOR_NAME "PublicDomain"
#endif /* !NDMOS_CONST_VENDOR_NAME */

#ifndef NDMOS_CONST_PRODUCT_NAME
#define NDMOS_CONST_PRODUCT_NAME "NDMJOB"
#endif /* !NDMOS_CONST_PRODUCT_NAME */

#ifndef NDMOS_CONST_PRODUCT_REVISION
#define NDMOS_CONST_PRODUCT_REVISION "0.0"
#endif /* !NDMOS_CONST_PRODUCT_REVISION */

/***
**** Replace xxx with your O/S short name.
**** A date code for the 000000 in YYMMDD format
**** is recommended. Another good choice is
**** YYWW where WW is the week of the year
**** between 01 and 52. It is free form,
**** so you can use whatever convention you like.
***/
#define NDMOS_CONST_NDMOS_REVISION "XXX-000000"


#endif /* NDMOS_ID == NDMOS_ID_XXX */

